ALTER TABLE users
  ADD COLUMN IF NOT EXISTS card_on_file BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS trial_variant TEXT CHECK (trial_variant IN ('nocard7','card14')) DEFAULT 'nocard7',
  ADD COLUMN IF NOT EXISTS trial_started_at TIMESTAMPTZ DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS trial_ends_at TIMESTAMPTZ DEFAULT NOW() + INTERVAL '7 days',
  ADD COLUMN IF NOT EXISTS trial_images_remaining INT DEFAULT 6,
  ADD COLUMN IF NOT EXISTS trial_videos_remaining INT DEFAULT 0;